services:
  kong-db:
    image: postgres:13
    container_name: kong-db
    environment:
      POSTGRES_USER: kong
      POSTGRES_DB: kong
      POSTGRES_PASSWORD: kong
    networks:
      - kong-net
    volumes:
      - kong-db-data:/var/lib/postgresql/data

  kong-migrations:
    image: kong:3.6
    command: kong migrations bootstrap
    depends_on:
      - kong-db
    environment:
      KONG_DATABASE: postgres
      KONG_PG_HOST: kong-db
      KONG_PG_PASSWORD: kong
      KONG_PASSWORD: kong
    networks:
      - kong-net

  kong:
    image: kong:3.6
    container_name: kong
    restart: always
    depends_on:
      - kong-db
      - kong-migrations
    environment:
      KONG_DATABASE: postgres
      KONG_PG_HOST: kong-db
      KONG_PG_PASSWORD: kong
      KONG_PROXY_ACCESS_LOG: /dev/stdout
      KONG_ADMIN_ACCESS_LOG: /dev/stdout
      KONG_PROXY_ERROR_LOG: /dev/stderr
      KONG_ADMIN_ERROR_LOG: /dev/stderr
      KONG_ADMIN_LISTEN: 0.0.0.0:8001
      KONG_LOG_LEVEL: debug
    ports:
      - "8000:8000"   # HTTP Pública Proxy
      - "8001:8001"   # Admin API sin TLS
      - "8444:8444"   # Admin API con TLS   
      - "8443:8443"   # HTTPS Pública Proxy
    networks:
      - nur-network
      - kong-net

#  konga:
#    image: pantsel/konga
#    container_name: konga
#    restart: always
#    depends_on:
#      - kong
#    environment:
#      DB_ADAPTER: postgres
#      DB_HOST: kong-db
#      DB_PORT: 5432
#      DB_USER: kong
#      DB_PASSWORD: kong
#      DB_DATABASE: kong
#      NODE_ENV: development
#    ports:
#      - "1337:1337"

  login-service:
    build: ./php-login    
    container_name: login-service
    networks:
      - kong-net

  kong-configurator:
    build:
      context: ./kong-config    
    container_name: kong-configurator
    depends_on:
      - kong
    networks:
      - kong-net

networks:
  kong-net:
    external: true
  nur-network:
    external: true
volumes:
  kong-db-data:
