services:
  consul:
    image: hashicorp/consul
    container_name: consul-server
    ports:
      - "8500:8500"
    volumes:
      - ./config:/consul/config
    networks:
      - evaluacion_nur-network
    command: agent -dev -client=0.0.0.0 -config-dir=/consul/config

networks:
  evaluacion_nur-network:
    external: true