services:
  consul:
    image: hashicorp/consul
    container_name: consul-server
    ports:
      - "8500:8500"
    volumes:
      - ./config:/consul/config
    networks:
      - nur-network
      - kong-net
    command: agent -dev -client=0.0.0.0 -config-dir=/consul/config

networks:
  nur-network:
    external: true  
  kong-net:
    external: true